### ISSUE TITLE
Occasional crash on rotation

### ISSUE THREAD

**Issue by jstubing** [willowtreeapps/vocable-android#185] opened 2020-04-27 22:27 UTC
The view binding object in each of our fragments has recently been made non-nullable. See PR: https://github.com/willowtreeapps/vocable-android/pull/167

The approach taken in the above PR assumes that the view binding won't be interacted with once the view is destroyed. This is generally taken care of by making sure that we communicate to the view via LiveData.

However, there appears to be some situations where we are doing something asynchronous and then we call back to a view without using LiveData and this can lead to a crash.

The most obvious example of this is on the keyboard fragment. With facetracking enabled, if you hover over a keyboard button and then rotate the device at just the right time, the app will crash.

It appears that pointing at a button will kick off a coroutine and after some delay execute an action. That action may contain code referencing a view binding which belongs to a view which has been destroyed (because of the rotation).

May need to re-evaluate how our onPointerEnter functions work. If a fragment gets destroyed then we need to cancel any running coroutines within the buttons such that they don't perform the action.

Alternatively, the quick fix is to revert the above PR which makes the view binding nullable again and reintroduces a ton of question marks throughout the code. 

Stack trace:

`2020-04-27 17:19:40.338 10160-10160/com.willowtree.vocable E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.willowtree.vocable, PID: 10160
    java.lang.Exception: View binding has been accessed after the view has been destroyed
        at com.willowtree.vocable.BaseFragment.getBinding(BaseFragment.kt:20)
        at com.willowtree.vocable.keyboard.KeyboardFragment.access$getBinding$p(KeyboardFragment.kt:28)
        at com.willowtree.vocable.keyboard.KeyboardFragment$populateKeys$$inlined$forEach$lambda$1.invoke(KeyboardFragment.kt:59)
        at com.willowtree.vocable.keyboard.KeyboardFragment$populateKeys$$inlined$forEach$lambda$1.invoke(KeyboardFragment.kt:28)
        at com.willowtree.vocable.customviews.ActionButton.performAction(ActionButton.kt:20)
        at com.willowtree.vocable.customviews.VocableButton$onPointerEnter$1$2.invokeSuspend(VocableButton.kt:68)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:7811)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)`

**Comment by jennydoesthings** [comment] 2020-09-18 17:41
I'm going to close this defect for a couple reasons:

1. I'm not able to reproduce it.  I know it's a timing bug which means it could be very hard to repro, but Cameron and I have been trying to repo it for a while.  This seems to indicate that it's not very common.
2. Primary use case for Vocable is a device in a fixed orientation.
3. In 1.4.1, we introduce better crash reporting. We will monitor the crashes coming in, and if we see this one, address the issue then.

**Closed by jennydoesthings** 2020-09-18 17:41 UTC
Labels: bug, priority - low
