### ISSUE TITLE
Add, edit and remove custom categories

### ISSUE THREAD

**Issue by kyliefk** [willowtreeapps/vocable-android#45] opened 2020-03-06 18:03 UTC
**Acceptance Criteria**
Users will have the ability to edit custom categories. 

1. Users can edit the name and location of custom categories. 
2. Only custom category names can be edited. 
3. Only custom categories can be removed or hidden. Preloaded categories can only be hidden. 
Note: The keyboard for editing category name will not have the speak button.
4. Custom categories can be added. When they are added, they are moved to the last position in the list of shown categories. 

**Design**

![image](https://user-images.githubusercontent.com/58052219/79493016-dd4d5c00-7fee-11ea-8bcf-d80676da77c9.png)

![image](https://user-images.githubusercontent.com/58052219/79492886-a6774600-7fee-11ea-8cca-4b026eb62f51.png)

![image](https://user-images.githubusercontent.com/58052219/79493634-bfccc200-7fef-11ea-9883-4719764c2567.png)

![image](https://user-images.githubusercontent.com/58052219/79493730-e8ed5280-7fef-11ea-99db-507ba85307a1.png)

**Comment by jennydoesthings** [comment] 2020-10-06 18:05
Duplicate of custom category work.

**Closed by jennydoesthings** 2020-10-06 18:05 UTC
Labels: Custom Category, v1.4
